server:
  port: 8082
hm:
  db:
    database: hm-cart
  swagger:
    title: 购物车文档
    package: com.hmall.cart.controller
  cart:
      maxSize: 2  #购物车购物上限
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8091 #控制台地址
      http-method-specify: true   #请求方式前缀
      datasource:
        ds2:
          nacos:
            server-addr: localhost:8848
            data-id: degrade.json
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade
feign:
  sentinel:
    enabled: true  # 开启Feign的的sentinel的整合

