server:
  port: 8084
hm:
  db:
    database: hm-trade
  swagger:
    title: 交易管理接口文档
    package: com.hmall.trade.controller
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: hmall
