server:
  port: 8084
spring:
  application:
    name: hm-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost
    gateway:
      routes:
        - id: item-service
          uri:
            lb://item-service
          predicates:
            - Path=/items/**,/search/**
        - id: cart-service
          uri:
            lb://cart-service
          predicates:
            - Path=/carts/**
      default-filters:
        - AddRequestHeader=truth, HuGeHandSome is very HandSome!
        - PrintAny=1,2,3
#        - name: PrintAny
#          args:
#            - a: 1
#              b: 2
#              c: 3


logging:
  level:
    com.hmall: debug
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.server.HttpServer: DEBUG
    org.springframework.web.filter: DEBUG
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

#jwt验证的配置
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123